sudo psql -U postgres -d "test" -c "INSERT INTO product(prod_name, prod_category, stocked) VALUES 
('apples', 'fruit', '1'), 
('oranges', 'fruit', '1'),
('grapes', 'fruit', '1'),
('banana', 'fruit', '1'),
('pears', 'fruit', '1'),
('pineapple', 'fruit', '1'),
('kiwi', 'fruit', '1'),
('plums', 'fruit', '1'),
('lemon', 'fruit', '1'),
('lime', 'fruit', '1'),
('steak', 'meat', '1'),
('chicken', 'meat', '1'),
('pork', 'meat', '1'),
('bacon', 'meat', '1'),
('sausages', 'meat', '1'),
('mince', 'meat', '1'),
('lamb', 'meat', '1'),
('duck', 'meat', '1'),
('turkey', 'meat', '1'),
('broccoli', 'vegetables', '1'),
('carrot', 'vegetables', '1'),
('potato', 'vegetables', '1'),
('sweet potato', 'vegetables', '1'),
('tomato', 'vegetables', '1'),
('onion', 'vegetables', '1'),
('mushroom', 'vegetables', '1'),
('sweetcorn', 'vegetables', '1'),
('courgette', 'vegetables', '1'),
('pepper', 'vegetables', '1'),
('bread', 'grains', '1'),
('tortillas', 'grains', '1'),
('cake', 'grains', '1'),
('baguette', 'grains', '1')
;"

